services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: